language: python
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install python-fontforge ttfautohint swig
  - cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - pip install python-coveralls
  - pip install Jinja2
  - pip install Scrapy
  - "pip install git+https://github.com/behdad/fonttools.git"
  - "pip install git+https://github.com/googlefonts/fontcrunch.git"
  - "pip install git+https://github.com/googlefonts/fontbakery.git"
script: LANG="en" python setup.py nosetests
after_success:
  coveralls
